pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.neoforged.net/releases/" }
        maven { url "https://maven.minecraftforge.net/" }
    }
}

include("Common", "Fabric", "NeoForge", "Forge")

apply from: "https://raw.githubusercontent.com/Fuzss/modresources/e6311c7c40cfb0fe4240f22fd80efbbe9c554585/gradle/v2/settings.gradle"
